### ISSUE TITLE
don't start SSH by default in the install environment

### ISSUE THREAD

**Issue by grahamc** [grahamc/packet-provision-nixos-ipxe#11]

**Comment by zimbatm** [comment]
Some tools like Ansible will try to SSH into the server and assume that it's "ready" the first time they manage to acquire a connection.

It means that the install environment will be assumed to be the final system and Ansible will fail because of the bad auth.

**Comment by grahamc** [comment]
Fixed in 06b7669065c69a2ac36ba58db4f3c5922cc04fe6 (not yet pushed)
