### ISSUE TITLE
accept nixos config from user data

### ISSUE THREAD

**Issue by grahamc** [grahamc/packet-provision-nixos-ipxe#2]

**Comment by abuibrahim** [comment]
being able to pass userdata.nix with cloud-init would tremendously help in fully automating the bringup of NixOS on packet.net - a la NixOps

**Comment by grahamc** [comment]
When applying NixOS configuration from user data, is it expected that if the userdata changed and the server is rebooted, the new config is downloaded and reapplied? Or, is the userdata only fetched at install time?

If userdata fails to apply, should the install fail, or should it skip the userdata and do a plain install?

Will users want to supply non-nixos-config userdata?

**Comment by grahamc** [comment]
cc @dtzWill

**Comment by grahamc** [comment]
![image](https://user-images.githubusercontent.com/76716/40893745-e3b7ee08-6771-11e8-99e7-045ca8a009ab.png)

**Comment by grahamc** [comment]
Closed in 4c1bc2d3b110c30c288e2661d5e5c6abc1ff9b36, not pushed yet.
