### ISSUE TITLE
forward logs to tinkerbell

### ISSUE THREAD

**Issue by grahamc** [grahamc/packet-provision-nixos-ipxe#3]

**Comment by mmlb** [comment]
This would be really nice to have. I've got a low priority task to fixup the osie (os install enviroenmt, cute right?) logging, possibly bypassing tinkerbell. But I hadn't thought about custom_ipxe or rancher/coreos/nixos. I'll have to ponder a bit more on it.

**Comment by grahamc** [comment]
Fixed in d1ff31fc670f62dbee18b25a1cd2e535ec1d02b9 (not pushed yet)
