### ISSUE TITLE
ssh accessible while provisioning

### ISSUE THREAD

**Issue by rbvermaa** [grahamc/packet-provision-nixos-ipxe#5]
when provisioning with the nixos 17.03, I was able to access ssh before provisioning was completed. It would be nice if SSH would only be available when provisioning/install is done. This will make it easier for nixops to see when provisioning is done by waiting for ssh.

**Comment by mmlb** [comment]
Shouldn't nixops use the api to determine when the machine has been fully provisioned instead? IIRC this is what ansible and terraform do.

**Comment by grahamc** [comment]
Fixed in  5f928687c0edc5989e193fb0da73c3b504fcf227 (not pushed yet.)
