### ISSUE TITLE
Maybe mention this is the official installer used by packet.net?

### ISSUE THREAD

**Issue by mmlb** [grahamc/packet-provision-nixos-ipxe#9]

**Comment by dtzWill** [comment]
I was wondering.... :)

**Comment by mmlb** [comment]
Yeah I figured it would be good to know, I can also add something to packet-images linking here.

**Comment by grahamc** [comment]
Fixed in 82131f5c0e90d2dd1f6384f16e532d230214189b, not pushed yet.
